export { Home } from './Home'
export { Popular } from './Popular'
export { TopRated } from './TopRated'
export { NowPlaying } from './NowPlaying'
export { Favorites } from './Favorites'
export { MovieSelection } from './MovieSelection'